### ISSUE TITLE
Feature request: variable sample sizes for different time points

### ISSUE THREAD

**Issue by natevmp** [fraterenz/hsc#84]
When creating a snapshop of the system at intermediate time points `t_i`, it would be nice to be to select a particular sample size for that time point, example through a vector `s_i` in the app arguments.

**Comment by fraterenz** [comment]
here https://github.com/fraterenz/hsc/blob/a0746a8f91f3a8bb1d20679bf62b613e960b4957/src/process.rs#L471C1-L471C53
